# Generated by Django 3.0.8 on 2020-07-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('ruc', models.IntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_comercial',
            new_name='clave',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ruc',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Empresa'),
        ),
    ]
