# Generated by Django 3.0.8 on 2020-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200722_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.CharField(choices=[('0', 'Visitante'), ('1', 'Usuario'), ('2', 'Admin')], default='0', max_length=1),
        ),
    ]
