# Generated by Django 3.0.8 on 2020-07-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200722_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=100),
        ),
    ]
