# Generated by Django 3.0.8 on 2020-07-23 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200723_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trafico_linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField()),
                ('trimestre', models.CharField(choices=[('I', 'Uno'), ('II', 'Dos'), ('III', 'Tercer'), ('IV', 'Cuarto')], max_length=3)),
                ('equipo', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=50)),
                ('lineas', models.BigIntegerField()),
                ('t_cursado', models.BigIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
