# Generated by Django 3.0.8 on 2020-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_trafico_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
