# Generated by Django 3.0.8 on 2020-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20200724_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fecha_inicio',
            field=models.CharField(max_length=20),
        ),
    ]
